### ISSUE TITLE
Consider Start-BitsTransfer for Download

### ISSUE THREAD

**Issue by darthmarx** [PaoloFrigo/scriptinglibrary#5]
Hi,

please consider using Start-BitsTransfer for Downloads, as it is much faster.

**Comment by PaoloFrigo** [comment]
Hi DarthMarx, 
   Thanks for your comment. Sorry I've totally missed it. 
Can you please provide more context or reference? What is exactly the script or function are you referring to?
Regards

**Comment by darthmarx** [comment]
This is the code I was referring to:
https://github.com/PaoloFrigo/scriptinglibrary/blob/727e79e0320a4598c34f655d8bd332cabdec2d57/Blog/PowerShell/Install-WAC.ps1#L23

**Comment by PaoloFrigo** [comment]
Hi DarthMarx,
   Frankly, for small files I don't pay much attention to it, but I do know what is the performance issue you are experiencing and referring to is caused in this case, because I faced/solved this multiple times. 
   
Bits in this scenario is not necessary much faster than Invoke-WebRequest, but what you see is the bottleneck caused by the progress bar that is more frequently updated by Invoke-WebRequest. 

If you want to test it yourself run this following snippet removing the progress bar on both cmd-lets:
```
$WAC_Online = "http://aka.ms/WACDownload"
$WAC_Installer = "C:\windows\Temp\wac.msi" 

$ProgressPreference = 'SilentlyContinue'
Measure-Command{Invoke-WebRequest -Uri $WAC_Online -OutFile $WAC_Installer}

Measure-Command{Start-BitsTransfer -Source $WAC_Online -Destination $WAC_Installer}
```
In my tests Invoke-WebRequest was always faster.
![image](https://user-images.githubusercontent.com/32283271/186328080-efacec83-f49a-4a75-8ea5-2be1670bff8c.png)

Bits is very convenient for larger files, but in this specific case I would still prefer invoke-webrequest. Let me know what you think.

Thanks,
Regards

**Comment by PaoloFrigo** [comment]
I will mark this as resolved.
